main:
  - identifier: categories
    name: 分类
    url: /categories/
    weight: 10
  - identifier: tags
    name: 标签
    url: /tags/
    weight: 20
  - identifier: search
    name: 搜索
    url: /search/
    weight: 30