# profile-mode
profileMode:
  enabled: true # needs to be explicitly set
  title: Justin Hu
  subtitle: "Many are called but few are chosen!"
  imageUrl: "<img location>"
  imageWidth: 120
  imageHeight: 120
  imageTitle: my image
  buttons:
    - name: 归档
      url: archives
    - name: 分类
      url: categories
    - name: 标签
      url: tags


footer:
  enable: true
  custom: >
    <p>All content is licensed under <a href='https://creativecommons.org/licenses/by-nc-nd/4.0/' target='_blank'>CC BY-NC-ND 4.0 (Attribution-NonCommercial-NoDerivatives 4.0 International).</a><br>
        <a href='/donate'><b>Donating</b></a> to charities and nonprofits to make the world a better place!<br>
        <a href='/visited_places' target='_blank'><b>My Visited Places!</b></a>
    </p>